import { db } from './firebase';
import { collection, writeBatch, doc, getDocs, query, limit, deleteDoc } from 'firebase/firestore';

const COMPOUND_DATA: [string, string][] = [
  ['Acetaminophen (Paracetamol)', 'CC(=O)NC1=CC=C(O)C=C1'],
  ['Ibuprofen', 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O'],
  ['Naproxen', 'CC(C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O'],
  ['Aspirin', 'CC(=O)OC1=CC=CC=C1C(=O)O'],
  ['Diclofenac', 'C1=CC=C(C(=C1)CC(=O)O)NC2=C(C=CC=C2Cl)Cl'],
  ['Celecoxib', 'CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(N)(=O)=O)C(F)(F)F'],
  ['Etoricoxib', 'CC1=CN=C(C=C1C2=CC=C(C=C2)S(=O)(=O)C)C3=CC=C(C=N3)Cl'],
  ['Ketoprofen', 'CC(C1=CC=CC(=C1)C(=O)C2=CC=CC=C2)C(=O)O'],
  ['Meloxicam', 'CC1=C(C(=NS1(=O)=O)NC2=NC=CS2)O'],
  ['Piroxicam', 'CC1=NC=CC=C1NC(=O)C2=C(O)C3=CC=CC=C3S(=O)(=O)N2C'],
  ['Indomethacin', 'CC1=C(C2=C(N1C(=O)C3=CC=C(C=C3)Cl)C=CC(=C2)OC)CC(=O)O'],
  ['Ketorolac', 'C1CC2=C(C1)N(C=C2C(=O)C3=CC=CC=C3)C(=O)O'],
  ['Morphine', 'CN1CCC23C4C1CC5=C2C(=C(C=C5)O)OC3C(C=C4)O'],
  ['Codeine', 'CN1CCC23C4C1CC5=C2C(=C(C=C5)OC)OC3C(C=C4)O'],
  ['Tramadol', 'CN(C)CC1(CCCCC1OC2=CC=CC(=C2)OC)O'],
  ['Oxycodone', 'CN1CCC23C4C1CC5=C2C(=C(C=C5)OC)OC3(C(CC4)=O)O'],
  ['Fentanyl', 'CCC(=O)N(C1=CC=CC=C1)C2CCN(CC2)CCC3=CC=CC=C3'],
  ['Lidocaine', 'CCN(CC)CC(=O)NC1=C(C)C=CC=C1C'],
  ['Bupivacaine', 'CCCCN1CCCCC1C(=O)NC2=C(C)C=CC=C2C'],
  ['Propofol', 'CC(C)C1=C(C=CC=C1C(C)C)O'],
  ['Ketamine', 'CN1C(CCCC1=O)(C2=CC=CC=C2Cl)O'],
  ['Amoxicillin', 'CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C'],
  ['Ciprofloxacin', 'C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O'],
  ['Azithromycin', 'CCC1C(C(C(N(CC(CC(C(C(C(C(C(=O)O1)C)OC2CC(C(C(O2)C)O)(C)OC)C)OC3C(C(CC(O3)C)N(C)C)O)(C)O)C)C)C)O)(C)O'],
  ['Doxorubicin', 'CC1C(C(CC(O1)OC2CC(CC3=C(C4=C(C(=C23)O)C(=O)C5=C(C4=O)C=CC=C5OC)O)(C(=O)CO)O)N)O'],
  ['Metformin', 'CN(C)C(=N)N=C(N)N'],
  ['Omeprazole', 'CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC'],
  ['Salbutamol (Albuterol)', 'CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O'],
  ['Glucose', 'C(C(C(C(C(CO)O)O)O)O)=O'],
  ['Lactose', 'C(C1C(C(C(C(O1)OC2C(OC(C(C2O)O)O)CO)O)O)O)O'],
  ['Magnesium Stearate', '[Mg+2].[O-]C(=O)CCCCCCCCCCCCCCCCC.[O-]C(=O)CCCCCCCCCCCCCCCCC']
];

// Adding the rest of the names from the user list without SMILES (placeholders)
const ADDITIONAL_NAMES: string[] = [
  'Naproxen', 'Aspirin', 'Diclofenac', 'Hydrocodone',
  'Hydromorphone', 'Methadone', 'Buprenorphine', 'Naloxone',
  'Naltrexone', 'Tapentadol', 'Oxymorphone', 'Lornoxicam',
  'Flurbiprofen', 'Mefenamic acid', 'Sulindac', 'Etodolac',
  'Diflunisal', 'Oxaprozin', 'Ropivacaine', 'Mepivacaine',
  'Prilocaine', 'Benzocaine', 'Procaine', 'Tetracaine',
  'Etomidate', 'Thiopental', 'Midazolam', 'Sevoflurane',
  'Desflurane', 'Isoflurane', 'Halothane', 'Succinylcholine',
  'Rocuronium', 'Vecuronium', 'Atracurium', 'Cisatracurium',
  'Pancuronium', 'Mivacurium', 'Dexmedetomidine', 'Remifentanil',
  'Alfentanil', 'Sufentanil', 'Nitrous oxide', 'Neostigmine',
  'Sugammadex', 'Flumazenil', 'Ampicillin', 'Penicillin G',
  'Penicillin V', 'Piperacillin', 'Oxacillin', 'Cloxacillin',
  'Flucloxacillin', 'Nafcillin', 'Ticarcillin', 'Cefalexin',
  'Cefazolin', 'Cefadroxil', 'Cefuroxime', 'Cefaclor',
  'Cefoxitin', 'Ceftriaxone', 'Cefotaxime', 'Ceftazidime',
  'Cefixime', 'Cefpodoxime', 'Cefdinir', 'Cefepime',
  'Ceftaroline', 'Imipenem', 'Meropenem', 'Ertapenem',
  'Doripenem', 'Aztreonam', 'Clavulanic acid', 'Sulbactam',
  'Tazobactam', 'Avibactam', 'Relebactam', 'Vaborbactam',
  'Gentamicin', 'Tobramycin', 'Amikacin', 'Streptomycin',
  'Neomycin', 'Plazomicin', 'Erythromycin', 'Clarithromycin',
  'Roxithromycin', 'Spiramycin', 'Telithromycin', 'Tetracycline',
  'Doxycycline', 'Minocycline', 'Tigecycline', 'Omadacycline',
  'Eravacycline', 'Levofloxacin', 'Moxifloxacin', 'Norfloxacin',
  'Ofloxacin', 'Gemifloxacin', 'Delafloxacin', 'Sulfamethoxazole',
  'Trimethoprim', 'Sulfadiazine', 'Vancomycin', 'Teicoplanin',
  'Dalbavancin', 'Oritavancin', 'Telavancin', 'Linezolid',
  'Tedizolid', 'Daptomycin', 'Metronidazole', 'Tinidazole',
  'Clindamycin', 'Rifampicin', 'Rifaximin', 'Chloramphenicol',
  'Nitrofurantoin', 'Fosfomycin', 'Colistin', 'Polymyxin B',
  'Fusidic acid', 'Mupirocin', 'Fidaxomicin', 'Lefamulin',
  'Cefiderocol', 'Fluconazole', 'Itraconazole', 'Voriconazole',
  'Posaconazole', 'Isavuconazole', 'Ketoconazole', 'Miconazole',
  'Clotrimazole', 'Econazole', 'Bifonazole', 'Terconazole',
  'Caspofungin', 'Micafungin', 'Anidulafungin', 'Rezafungin',
  'Terbinafine', 'Naftifine', 'Flucytosine', 'Griseofulvin',
  'Ciclopirox', 'Amorolfine', 'Tolnaftate', 'Chloroquine',
  'Hydroxychloroquine', 'Primaquine', 'Quinine', 'Mefloquine',
  'Atovaquone', 'Proguanil', 'Lumefantrine', 'Piperaquine',
  'Albendazole', 'Mebendazole', 'Praziquantel', 'Nitazoxanide',
  'Pyrimethamine', 'Sulfadoxine', 'Miltefosine', 'Pentamidine',
  'Suramin', 'Benznidazole', 'Nifurtimox', 'Ivermectin',
  'Diethylcarbamazine', 'Pyrantel', 'Oxamniquine', 'Zidovudine',
  'Lamivudine', 'Emtricitabine', 'Tenofovir disoproxil', 'Tenofovir alafenamide',
  'Abacavir', 'Stavudine', 'Efavirenz', 'Nevirapine',
  'Rilpivirine', 'Etravirine', 'Doravirine', 'Lopinavir',
  'Ritonavir', 'Atazanavir', 'Darunavir', 'Fosamprenavir',
  'Tipranavir', 'Raltegravir', 'Elvitegravir', 'Dolutegravir',
  'Bictegravir', 'Cabotegravir', 'Maraviroc', 'Sofosbuvir',
  'Ledipasvir', 'Velpatasvir', 'Daclatasvir', 'Glecaprevir',
  'Pibrentasvir', 'Grazoprevir', 'Elbasvir', 'Entecavir',
  'Ribavirin', 'Oseltamivir', 'Zanamivir', 'Baloxavir marboxil',
  'Peramivir', 'Acyclovir', 'Valacyclovir', 'Famciclovir',
  'Ganciclovir', 'Valganciclovir', 'Foscarnet', 'Cidofovir',
  'Nirmatrelvir', 'Molnupiravir', 'Remdesivir', 'Letermovir',
  'Brincidofovir', 'Fluoxetine', 'Sertraline', 'Paroxetine',
  'Citalopram', 'Escitalopram', 'Fluvoxamine', 'Venlafaxine',
  'Duloxetine', 'Desvenlafaxine', 'Milnacipran', 'Levomilnacipran',
  'Amitriptyline', 'Nortriptyline', 'Imipramine', 'Clomipramine',
  'Desipramine', 'Doxepin', 'Bupropion', 'Mirtazapine',
  'Trazodone', 'Vortioxetine', 'Vilazodone', 'Agomelatine',
  'Reboxetine', 'Esketamine', 'Phenelzine', 'Tranylcypromine',
  'Selegiline', 'Haloperidol', 'Chlorpromazine', 'Fluphenazine',
  'Perphenazine', 'Trifluoperazine', 'Thioridazine', 'Loxapine',
  'Pimozide', 'Olanzapine', 'Risperidone', 'Quetiapine',
  'Aripiprazole', 'Ziprasidone', 'Clozapine', 'Paliperidone',
  'Asenapine', 'Iloperidone', 'Lurasidone', 'Cariprazine',
  'Brexpiprazole', 'Lumateperone', 'Diazepam', 'Alprazolam',
  'Clonazepam', 'Lorazepam', 'Oxazepam', 'Temazepam',
  'Triazolam', 'Chlordiazepoxide', 'Clorazepate', 'Zolpidem',
  'Zaleplon', 'Eszopiclone', 'Zopiclone', 'Buspirone',
  'Hydroxyzine', 'Ramelteon', 'Suvorexant', 'Lemborexant',
  'Daridorexant', 'Phenytoin', 'Carbamazepine', 'Oxcarbazepine',
  'Eslicarbazepine', 'Valproic acid', 'Lamotrigine', 'Levetiracetam',
  'Brivaracetam', 'Topiramate', 'Zonisamide', 'Gabapentin',
  'Pregabalin', 'Lacosamide', 'Perampanel', 'Rufinamide',
  'Tiagabine', 'Vigabatrin', 'Phenobarbital', 'Ethosuximide',
  'Clobazam', 'Cenobamate', 'Levodopa', 'Carbidopa',
  'Pramipexole', 'Ropinirole', 'Rotigotine', 'Rasagiline',
  'Safinamide', 'Entacapone', 'Tolcapone', 'Opicapone',
  'Amantadine', 'Trihexyphenidyl', 'Benztropine', 'Methylphenidate',
  'Dextroamphetamine', 'Lisdexamfetamine', 'Atomoxetine', 'Viloxazine',
  'Guanfacine', 'Donepezil', 'Rivastigmine', 'Galantamine',
  'Memantine', 'Lithium', 'Acamprosate', 'Disulfiram',
  'Varenicline', 'Sumatriptan', 'Rizatriptan', 'Zolmitriptan',
  'Naratriptan', 'Eletriptan', 'Almotriptan', 'Frovatriptan',
  'Lasmiditan', 'Ubrogepant', 'Rimegepant', 'Atogepant',
  'Metoprolol', 'Atenolol', 'Propranolol', 'Carvedilol',
  'Bisoprolol', 'Labetalol', 'Nebivolol', 'Esmolol',
  'Sotalol', 'Enalapril', 'Lisinopril', 'Ramipril',
  'Captopril', 'Perindopril', 'Fosinopril', 'Quinapril',
  'Benazepril', 'Trandolapril', 'Losartan', 'Valsartan',
  'Irbesartan', 'Candesartan', 'Olmesartan', 'Telmisartan',
  'Azilsartan', 'Amlodipine', 'Nifedipine', 'Diltiazem',
  'Verapamil', 'Felodipine', 'Nicardipine', 'Nimodipine',
  'Clevidipine', 'Lercanidipine', 'Furosemide', 'Hydrochlorothiazide',
  'Chlorthalidone', 'Indapamide', 'Metolazone', 'Spironolactone',
  'Eplerenone', 'Finerenone', 'Amiloride', 'Triamterene',
  'Torsemide', 'Bumetanide', 'Atorvastatin', 'Rosuvastatin',
  'Simvastatin', 'Pravastatin', 'Lovastatin', 'Fluvastatin',
  'Pitavastatin', 'Ezetimibe', 'Fenofibrate', 'Gemfibrozil',
  'Bempedoic acid', 'Colestyramine', 'Colesevelam', 'Amiodarone',
  'Flecainide', 'Propafenone', 'Quinidine', 'Procainamide',
  'Disopyramide', 'Mexiletine', 'Dronedarone', 'Dofetilide',
  'Ibutilide', 'Adenosine', 'Nitroglycerin', 'Isosorbide mononitrate',
  'Isosorbide dinitrate', 'Ranolazine', 'Ivabradine', 'Hydralazine',
  'Minoxidil', 'Prazosin', 'Doxazosin', 'Terazosin',
  'Clonidine', 'Methyldopa', 'Moxonidine', 'Sacubitril',
  'Vericiguat', 'Warfarin', 'Fondaparinux', 'Rivaroxaban',
  'Apixaban', 'Edoxaban', 'Dabigatran', 'Clopidogrel',
  'Prasugrel', 'Ticagrelor', 'Dipyridamole', 'Cilostazol',
  'Vorapaxar', 'Argatroban', 'Bivalirudin', 'Sildenafil',
  'Tadalafil', 'Bosentan', 'Ambrisentan', 'Macitentan',
  'Riociguat', 'Selexipag', 'Iloprost', 'Digoxin',
  'Tretinoin', 'Adapalene', 'Tazarotene', 'Trifarotene',
  'Benzoyl peroxide', 'Azelaic acid', 'Isotretinoin', 'Calcipotriol',
  'Clobetasol', 'Pimecrolimus', 'Crisaborole', 'Tapinarof',
  'Acitretin', 'Dapsone', 'Monobenzone', 'Hydroquinone',
  'Salicylic acid', 'Iohexol', 'Iodixanol', 'Ioversol',
  'Iopamidol', 'Iomeprol', 'Barium sulfate', 'Gadolinium chelates',
  'Technetium compounds', 'Iobenguane', 'Florbetapir', 'Florbetaben',
  'Flutemetamol', 'Glipizide', 'Glyburide', 'Glimepiride',
  'Gliclazide', 'Tolbutamide', 'Pioglitazone', 'Rosiglitazone',
  'Sitagliptin', 'Saxagliptin', 'Alogliptin', 'Linagliptin',
  'Empagliflozin', 'Dapagliflozin', 'Canagliflozin', 'Ertugliflozin',
  'Repaglinide', 'Nateglinide', 'Acarbose', 'Miglitol',
  'Levothyroxine', 'Liothyronine', 'Methimazole', 'Propylthiouracil',
  'Carbimazole', 'Prednisone', 'Prednisolone', 'Methylprednisolone',
  'Dexamethasone', 'Hydrocortisone', 'Betamethasone', 'Fludrocortisone',
  'Deflazacort', 'Ethinyl estradiol', 'Estradiol', 'Progesterone',
  'Norethindrone', 'Levonorgestrel', 'Desogestrel', 'Drospirenone',
  'Cyproterone', 'Testosterone', 'Oxandrolone', 'Danazol',
  'Tamoxifen', 'Raloxifene', 'Anastrozole', 'Letrozole',
  'Exemestane', 'Clomiphene', 'Mifepristone', 'Finasteride',
  'Dutasteride', 'Flutamide', 'Bicalutamide', 'Alendronate',
  'Risedronate', 'Ibandronate', 'Zoledronic acid', 'Calcitriol',
  'Cholecalciferol', 'Osilodrostat', 'Mitotane', 'Metyrapone',
  'Esomeprazole', 'Lansoprazole', 'Pantoprazole', 'Rabeprazole',
  'Dexlansoprazole', 'Vonoprazan', 'Famotidine', 'Cimetidine',
  'Nizatidine', 'Sucralfate', 'Misoprostol', 'Metoclopramide',
  'Domperidone', 'Ondansetron', 'Granisetron', 'Palonosetron',
  'Aprepitant', 'Netupitant', 'Rolapitant', 'Loperamide',
  'Diphenoxylate', 'Lactulose', 'Linaclotide', 'Plecanatide',
  'Lubiprostone', 'Prucalopride', 'Tenapanor', 'Alosetron',
  'Eluxadoline', 'Mesalamine', 'Sulfasalazine', 'Olsalazine',
  'Balsalazide', 'Ursodeoxycholic acid', 'Obeticholic acid', 'Chenodeoxycholic acid',
  'Bismuth subsalicylate', 'Hydroxyurea', 'Roxadustat', 'Vadadustat',
  'Daprodustat', 'Anagrelide', 'Eltrombopag', 'Avatrombopag',
  'Luspatercept (peptide)', 'Azathioprine', 'Mycophenolate mofetil', 'Cyclosporine',
  'Tacrolimus', 'Sirolimus', 'Everolimus', 'Leflunomide',
  'Tofacitinib', 'Baricitinib', 'Upadacitinib', 'Filgotinib',
  'Colchicine', 'Allopurinol', 'Febuxostat', 'Probenecid',
  'Apremilast', 'Hydroxychloroquine', 'Cyclobenzaprine', 'Baclofen',
  'Carisoprodol', 'Methocarbamol', 'Tizanidine', 'Dantrolene',
  'Orphenadrine', 'Chlorzoxazone', 'Alendronate', 'Risedronate',
  'Oxytocin (synthetic)', 'Misoprostol', 'Dinoprostone', 'Mifepristone',
  'Levonorgestrel (EC)', 'Magnesium sulfate', 'Nifedipine (tocolytic)', 'Betamethasone (antenatal)',
  'Carbetocin', 'Atosiban', 'Terbutaline (tocolytic)', 'Cyclophosphamide',
  'Ifosfamide', 'Chlorambucil', 'Melphalan', 'Busulfan',
  'Bendamustine', 'Carmustine', 'Lomustine', 'Dacarbazine',
  'Temozolomide', 'Cisplatin', 'Carboplatin', 'Oxaliplatin',
  'Methotrexate', 'Pemetrexed', '5-Fluorouracil', 'Capecitabine',
  'Gemcitabine', 'Cytarabine', 'Azacitidine', 'Decitabine',
  'Fludarabine', 'Cladribine', 'Clofarabine', 'Hydroxyurea',
  'Irinotecan', 'Topotecan', 'Etoposide', 'Imatinib',
  'Dasatinib', 'Nilotinib', 'Bosutinib', 'Ponatinib',
  'Asciminib', 'Gefitinib', 'Erlotinib', 'Afatinib',
  'Osimertinib', 'Dacomitinib', 'Lapatinib', 'Neratinib',
  'Tucatinib', 'Sorafenib', 'Sunitinib', 'Pazopanib',
  'Axitinib', 'Regorafenib', 'Cabozantinib', 'Vandetanib',
  'Lenvatinib', 'Alectinib', 'Ceritinib', 'Crizotinib',
  'Brigatinib', 'Lorlatinib', 'Trametinib', 'Cobimetinib',
  'Binimetinib', 'Selumetinib', 'Vemurafenib', 'Dabrafenib',
  'Encorafenib', 'Ibrutinib', 'Acalabrutinib', 'Zanubrutinib',
  'Idelalisib', 'Copanlisib', 'Alpelisib', 'Venetoclax',
  'Palbociclib', 'Ribociclib', 'Abemaciclib', 'Ruxolitinib',
  'Vismodegib', 'Sonidegib', 'Glasdegib', 'Ivosidenib',
  'Enasidenib', 'Midostaurin', 'Gilteritinib', 'Fedratinib',
  'Avapritinib', 'Ripretinib', 'Capmatinib', 'Selpercatinib',
  'Larotrectinib', 'Entrectinib', 'Adagrasib', 'Sotorasib',
  'Olaparib', 'Niraparib', 'Rucaparib', 'Talazoparib',
  'Enzalutamide', 'Apalutamide', 'Darolutamide', 'Abiraterone',
  'Thalidomide', 'Lenalidomide', 'Pomalidomide', 'Bortezomib',
  'Carfilzomib', 'Ixazomib', 'Vorinostat', 'Romidepsin',
  'Belinostat', 'Panobinostat', 'Arsenic trioxide', 'Tretinoin (ATRA)',
  'Tazemetostat', 'Olutasidenib', 'Fulvestrant', 'Mechlorethamine',
  'Epirubicin', 'Mitoxantrone', 'Latanoprost', 'Bimatoprost',
  'Travoprost', 'Tafluprost', 'Timolol ophthalmic', 'Dorzolamide',
  'Brinzolamide', 'Brimonidine', 'Apraclonidine', 'Pilocarpine',
  'Tropicamide', 'Cyclopentolate', 'Ketorolac ophthalmic', 'Nepafenac',
  'Bromfenac', 'Fluorometholone', 'Loteprednol', 'Lifitegrast',
  'Verteporfin', 'Ganciclovir gel', 'Levalbuterol', 'Terbutaline',
  'Salmeterol', 'Formoterol', 'Indacaterol', 'Vilanterol',
  'Olodaterol', 'Ipratropium', 'Tiotropium', 'Glycopyrronium',
  'Aclidinium', 'Umeclidinium', 'Theophylline', 'Aminophylline',
  'Fluticasone', 'Budesonide', 'Beclomethasone', 'Mometasone',
  'Ciclesonide', 'Montelukast', 'Zafirlukast', 'Zileuton',
  'Ivacaftor', 'Lumacaftor', 'Tezacaftor', 'Elexacaftor',
  'Roflumilast', 'Dextromethorphan', 'Guaifenesin', 'Benzonatate',
  'Acetylcysteine', 'Erdosteine', 'Ambroxol', 'Acetylcysteine (antidote)',
  'Deferoxamine', 'Deferasirox', 'Deferiprone', 'Succimer (DMSA)',
  'Penicillamine', 'Pralidoxime', 'Methylene blue', 'Fomepizole',
  'Dimercaprol (BAL)', 'Glucagon', 'Activated charcoal', 'Atropine',
  'Physostigmine', 'Pyridostigmine', 'Tamsulosin', 'Alfuzosin',
  'Silodosin', 'Oxybutynin', 'Tolterodine', 'Solifenacin',
  'Darifenacin', 'Fesoterodine', 'Mirabegron', 'Vibegron',
  'Vardenafil', 'Avanafil', 'Bethanechol', 'Phenazopyridine',
  'Flavoxate', 'Folic acid', 'Cyanocobalamin (B12)', 'Pyridoxine (B6)',
  'Thiamine (B1)', 'Riboflavin (B2)', 'Niacin (B3)', 'Ascorbic acid',
  'Cholecalciferol (D3)', 'Ergocalciferol (D2)', 'Phytonadione (K1)', 'Retinol (Vitamin A)',
  'Biotin', 'Iron sulfate', 'Ferrous gluconate', 'Calcium carbonate',
  'Magnesium oxide', 'Zinc sulfate', 'Potassium chloride'
];

export async function seedDatabase() {
  const compoundsRef = collection(db, 'compounds');
  
  // Quick check - only seed if the database is functionally empty
  const existingSnap = await getDocs(query(compoundsRef, limit(1)));
  if (!existingSnap.empty) return;

  console.log('Initializing database library...');
  
  const finalMap = new Map<string, string>();
  COMPOUND_DATA.forEach(([name, smiles]) => finalMap.set(name, smiles));
  ADDITIONAL_NAMES.forEach((name) => {
    if (!finalMap.has(name)) finalMap.set(name, "");
  });

  const finalArray = Array.from(finalMap.entries());
  const CHUNK_SIZE = 400;
  
  for (let i = 0; i < finalArray.length; i += CHUNK_SIZE) {
    const chunk = finalArray.slice(i, i + CHUNK_SIZE);
    const batch = writeBatch(db);
    
    chunk.forEach(([name, smiles]) => {
      const docId = name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      batch.set(doc(db, 'compounds', docId), {
        name,
        smiles,
        createdAt: new Date().toISOString()
      });
    });
    
    await batch.commit();
  }
}
